/*
 * Writes docs/CATALOGUE_STATUS.md - every catalogue variant, whether its dimension
 * table is filled or still awaiting data, and the client PDF it came from.
 *
 * The table is read straight from src/lib, so it always matches what the site shows:
 *   bun run catalogue:status          regenerate the file
 *   bun run catalogue:status --check  exit 1 if the file is out of date
 *
 * Plain .mjs so Node runs it without a build step (Node 22.18+ strips the types
 * from the imported .ts files). Bun resolves the "@/" alias itself.
 */

import { readFileSync, writeFileSync } from "node:fs";
import * as nodeModule from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = join(ROOT, "docs", "CATALOGUE_STATUS.md");

/* Node needs help with the "@/" alias and extensionless .ts imports that Next resolves. */
if (typeof nodeModule.registerHooks === "function") {
  nodeModule.registerHooks({
    resolve(specifier, context, nextResolve) {
      if (specifier.startsWith("@/")) {
        const file = join(ROOT, "src", `${specifier.slice(2)}.ts`);
        return nextResolve(pathToFileURL(file).href, context);
      }
      return nextResolve(specifier, context);
    },
  });
}

const lib = (file) => import(pathToFileURL(join(ROOT, "src", "lib", file)).href);

const { CATALOGUE_FAMILIES } = await lib("catalogue-tree.ts");
const { tableFor } = await lib("catalogue-tables.ts");

const products = [];

for (const family of CATALOGUE_FAMILIES) {
  for (const type of family.types) {
    for (const variant of type.variants) {
      products.push({ family, type, variant, table: tableFor(family.id, type.id, variant.id) });
    }
  }
}

/*
 * A table that shares its rows with another variant's table was not supplied as its
 * own sheet - it reuses that variant's (e.g. 316 pages built from the 304 sheet).
 */
const reusedFrom = (product) =>
  products
    .slice(0, products.indexOf(product))
    .find((other) => other.table?.rows === product.table.rows);

const productName = ({ type, variant }) => `${type.name} - ${variant.name}`;

const lines = products.map((product, index) => {
  const { family, table } = product;

  if (!table) {
    return `| ${index + 1} | ${family.name} | ${productName(product)} | Awaiting data | - | - |`;
  }

  const donor = reusedFrom(product);
  const source = donor
    ? `\`${table.source}\` (reuses the ${donor.variant.name} sheet)`
    : `\`${table.source}\``;

  return `| ${index + 1} | ${family.name} | ${productName(product)} | Complete | ${table.rows.length} | ${source} |`;
});

const pending = products.filter((product) => !product.table);

const markdown = `# Catalogue status

<!-- Generated by scripts/catalogue-status.mjs - do not edit by hand. Run: bun run catalogue:status -->

Every variant page under \`/products\`, read from \`src/lib/catalogue-tree.ts\` and
\`src/lib/catalogue-tables.ts\`. Source PDFs live in \`docs/catalogue-sources/\`.

**${products.length - pending.length} of ${products.length} complete - ${pending.length} awaiting data.**

| # | Family | Product | Status | Sizes | Source PDF |
|---|---|---|---|---|---|
${lines.join("\n")}

## Awaiting data

${pending.length === 0 ? "None." : pending.map((product) => `- ${productName(product)}`).join("\n")}
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    /* Missing file counts as out of date. */
  }
  if (current !== markdown) {
    console.error("docs/CATALOGUE_STATUS.md is out of date. Run: bun run catalogue:status");
    process.exit(1);
  }
  console.log("docs/CATALOGUE_STATUS.md is up to date.");
} else {
  writeFileSync(OUTPUT, markdown);
  console.log(
    `Wrote docs/CATALOGUE_STATUS.md - ${products.length - pending.length}/${products.length} complete.`,
  );
}
